### ISSUE TITLE
 Error: You should create pull-point subscription first / Can not connect

### ISSUE THREAD

**Issue by WhiteLionATX** [bartbutenaers/node-red-contrib-onvif-nodes#32] opened 2022-09-06 15:37 UTC
I ve only one device and connection makes for whatever reasons problems. (Sometimes works, sometimes not) Cam is working fine while disconnects appear. Using "OnVif events" / action "Start listening". Node Red crashes:

`6 Sep 17:23:30 - [error] [onvif-events:817ba9091c11e67e] This node is not connected to a device
6 Sep 17:23:31 - [info] [mqtt-broker:f55c6c0d.194bb] Connected to broker: mqtt://localhost:1883
pam_unix(sudo:session): session closed for user root
6 Sep 17:23:37 - [error] [onvif-config:MyCamTest58] The device is now connected, but the data cannot be loaded
6 Sep 17:30:16 - [red] Uncaught Exception:
6 Sep 17:30:16 - [error] Error: You should create pull-point subscription first!
    at Cam.pullMessages (/home/pi/.node-red/node_modules/onvif/lib/events.js:188:10)
    at Cam._eventPull (/home/pi/.node-red/node_modules/onvif/lib/events.js:309:9)
    at Cam.<anonymous> (/home/pi/.node-red/node_modules/onvif/lib/events.js:100:13)
    at parseSOAPString (/home/pi/.node-red/node_modules/onvif/lib/utils.js:108:3)
    at IncomingMessage.<anonymous> (/home/pi/.node-red/node_modules/onvif/lib/cam.js:246:4)
    at IncomingMessage.emit (node:events:539:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.
nodered.service: Service RestartSec=20s expired, scheduling restart.
nodered.service: Scheduled restart job, restart counter is at 1.
Stopped Node-RED graphical event wiring tool.
`

**Comment by bartbutenaers** [comment] 2022-09-07 18:53
Hi @WhiteLionATX,

I am going to close this issue, because it is a duplicate of [this](https://github.com/bartbutenaers/node-red-contrib-onvif-nodes/issues/28) one.  Otherwise it becomes difficult to keep track of it all.

As you can see in the other issue, I have asked for help from the repo that I am using under the cover...

Bart

**Closed as completed by bartbutenaers** 2022-09-07 18:53 UTC
